In [ ]:
set1 = (1, "apple", (22, 23, 24), 12.4587)
print(set1)

set2 = {22, 28.6489, "python", (12, 45, 78)}
print(set2)

(1, 'apple', (22, 23, 24), 12.4587)
{'python', 28.6489, 22, (12, 45, 78)}


In [ ]:
  import numpy as np

  x = np.array([[1,2], [4,5]])
  y = np.array([[6,7], [9, 10]])

  print("addition of matrix")
  print(np.add(x,y))

  print("subtraction of matrix")
  print(np.subtract(x,y))

addition of matrix
[[ 7  9]
 [13 15]]
subtraction of matrix
[[-5 -5]
 [-5 -5]]


In [ ]:
a = np.matrix("1,2,3; 4,5,6; 7,8,9")
[b = np.array(a)
print(b)

print(b.T)

In [ ]:
import numpy as np

a = ([12,13, 54],[18,14, 88])
b = ([[12, 13], [14, 15]])
c = ([[67, 6, 8], [54, 94, 77]])

print(np.add(a,c, ))

[[ 79  19  62]
 [ 72 108 165]]


In [ ]:
def f_1():
  print("hello!!")

  def f_2():
    print("HELLO!!")

  f_2()

f_1()

hello!!
HELLO!!


In [ ]:
import csv
file=open('/content/drive/MyDrive/Book1.csv','r')
csv_book1=list(csv.reader(file))
print(csv_book1)
file=open('/content/drive/MyDrive/excel_2.csv','r')
csv_book2=list(csv.reader(file))
print(csv_book2)

[['Sr. No.', 'Employee name ', "Employee I'D", 'Age ', 'Date Of birth'], ['1', 'Juber Maindarge', '202201090001', '23', '11/1/2004'], ['2', 'Shruti Garad ', '202201090002', '26', '11/2/2004'], ['3', 'Yash Kumbhar', '202201090114', '28', '11/3/2004'], ['4', 'Swastik Paratkar', '202201090004', '25', '11/4/2004'], ['5', 'Ashraf Shaikh', '202201090004', '21', '11/5/2004'], ['6', 'Bhagyashree Thakur', '202201090005', '29', '11/6/2004'], ['7', 'Hitarth Paliwal', '202201090006', '28', '11/7/2004'], ['8', 'Vaibhav ', '202201090007', '32', '11/8/2004'], ['9', 'Ramani Vemula ', '202201090008', '26', '11/9/2004'], ['10', 'Neil Desai', '202201090009', '24', '11/10/2004'], ['11', 'Gandharva Jhadav ', '2022010900010', '29', '11/11/2004'], ['12', 'Shalom Jadhav ', '2022010900011', '25', '11/12/2004'], ['13', 'Prathemesh Chavan ', '2022010900012', '33', '11/13/2004'], ['14', 'Harashada Thorat', '202201090020', '30', '11/14/2004'], ['15', 'Om Dhakne ', '202201090013', '33', '11/15/2004'], ['16', 'Vaish

In [ ]:
#import csv
#file= open('','r')
#csv_excel_1 = list(csv.reader(file))
#print(csv_excel.1)
#file= open('','r')
#csv_excel_2 = list(csv.reader(file))
#print(csv_excel.2)


In [ ]:
print("hello, good morning")
print("using pandas")

import pandas as pd

df=pd.read_csv(r'/content/drive/MyDrive/Book1.csv')
print(df)
df1=pd.read_csv(r'/content/drive/MyDrive/excel_2.csv')
print(df1)


hello, good morning
using pandas
    Sr. No.      Employee name    Employee I'D  Age  Date Of birth
0         1     Juber Maindarge   202201090001    23     11/1/2004
1         2       Shruti Garad    202201090002    26     11/2/2004
2         3        Yash Kumbhar   202201090114    28     11/3/2004
3         4    Swastik Paratkar   202201090004    25     11/4/2004
4         5       Ashraf Shaikh   202201090004    21     11/5/2004
5         6  Bhagyashree Thakur   202201090005    29     11/6/2004
6         7     Hitarth Paliwal   202201090006    28     11/7/2004
7         8            Vaibhav    202201090007    32     11/8/2004
8         9      Ramani Vemula    202201090008    26     11/9/2004
9        10          Neil Desai   202201090009    24    11/10/2004
10       11   Gandharva Jhadav   2022010900010    29    11/11/2004
11       12      Shalom Jadhav   2022010900011    25    11/12/2004
12       13  Prathemesh Chavan   2022010900012    33    11/13/2004
13       14    Harashada Thor

In [ ]:
#import csv
#df = open(r'/content/drive/MyDrive/Book1.xlsx')
#x = df.read_csv()
#print(x)
time= int(input("enter time in seconds: "))
int(time)
m= time//60
s= time%60
print(m,"minutes",s, "seconds")

enter time in seconds: 344
5 minutes 44 seconds


In [ ]:
x=10
y=0
while x>y:
  print(x,y)
  x=x-1
  y=y+1

10 0
9 1
8 2
7 3
6 4
