In [ ]:
set1 = (1, "apple", (22, 23, 24), 12.4587)
print(set1)

set2 = {22, 28.6489, "python", (12, 45, 78)}
print(set2)

(1, 'apple', (22, 23, 24), 12.4587)
{(12, 45, 78), 'python', 28.6489, 22}


In [ ]:
# Pandas is a Python library used for working with data sets

import pandas as pd


In [ ]:
#NumPy is a Python library used for working with arrays


In [ ]:
#A stack is an abstract data type that serves as a collection of elements with two principal operations which are push and pop.
# In contrast, a linked list is a linear collection of data elements whose order is not given by their location in memory
#Stacks are less flexible than lists, but are easier to implement, and more efficient (for those operations they can do).




In [ ]:
  import numpy as np

  x = np.array([[1,2], [4,5]])
  y = np.array([[6,7], [9, 10]])

  print("addition of matrix")
  print(np.add(x,y))

  print("subtraction of matrix")
  print(np.subtract(x,y))

addition of matrix
[[ 7  9]
 [13 15]]
subtraction of matrix
[[-5 -5]
 [-5 -5]]


In [ ]:
a = np.matrix("1,2,3; 4,5,6; 7,8,9")
[b = np.array(a)
print(b)

print(b.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np

a = ([12,13, 54],[18,14, 88])
b = ([[12, 13], [14, 15]])
c = ([[67, 6, 8], [54, 94, 77]])

print(np.add(a,c, ))

[[ 79  19  62]
 [ 72 108 165]]


In [ ]:
a= np.matrix("1,2,3; 4,5,6; 7,8,9")
print(a)

print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
def outer():
  print("outer function")

  def inner():
    print("inner function")

  inner()

outer()

outer function
inner function


In [ ]:
def add():
  a= 2
  b=5
  c =a+b
  print(c)

  def sub():
    a= 5
    b=4
    c=a-b
    s= (a-b)
    print(s)

  sub()
add()

7
1


In [ ]:
a=float('12')
b=float('12.5')
c=int('12')

print(a)
print(b)
print(c)


12.0
12.5
12


In [ ]:
time